# Generated by Django 3.1.1 on 2020-10-05 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='الإسم')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='وصف الإمتحان')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='الإسم')),
                ('TotalResult', models.IntegerField(verbose_name='النتيجة النهائية')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.category')),
            ],
            options={
                'verbose_name': 'exam',
                'verbose_name_plural': 'exams',
            },
        ),
    ]
