# Generated by Django 3.1.1 on 2020-10-06 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_finalresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=255, verbose_name='السؤال')),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('TrueAnswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.trueanswer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.category')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
