# Generated by Django 3.1.2 on 2020-10-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionType',
            field=models.IntegerField(blank=True, choices=[(1, 'اختيار من متعدد'), (2, 'مقالى')], max_length=255, verbose_name='نوع السؤال'),
        ),
    ]
