# Generated by Django 3.1.2 on 2020-10-06 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20201007_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trueanswer',
            name='question',
        ),
    ]
