# Generated by Django 3.1.2 on 2020-10-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_trueanswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='الصوره'),
        ),
    ]
