# Generated by Django 3.1.2 on 2020-10-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_question_question_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trueanswer',
            name='Exam',
        ),
        migrations.RemoveField(
            model_name='trueanswer',
            name='Question',
        ),
        migrations.RemoveField(
            model_name='trueanswer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_photo',
        ),
        migrations.AddField(
            model_name='exam',
            name='question_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='TrueAnswer',
        ),
    ]
