# Generated by Django 3.1.2 on 2020-10-16 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20201016_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Exam',
            new_name='exam',
        ),
        migrations.RemoveField(
            model_name='finalresult',
            name='result',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionType',
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(default='<function now at 0x000001B8A356D040>', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(default='<function now at 0x000001B8A356D040>', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(default='<function now at 0x000001B8A356D040>', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(default='<function now at 0x000001B8A356D040>', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_number',
            field=models.SmallIntegerField(blank=True, choices=[(20, '20'), (25, '25'), (30, '30'), (50, '50'), (100, '100')], null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('A', 'option1'), ('B', 'option2'), ('C', 'option3'), ('D', 'option4')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default='<function now at 0x000001B8A356D040>', max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_no', models.PositiveIntegerField(default=0)),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('ques', models.ManyToManyField(to='exam.Question')),
            ],
            options={
                'verbose_name': 'set',
                'verbose_name_plural': 'sets',
            },
        ),
    ]
