# Generated by Django 3.1.2 on 2020-10-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20201016_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='set_no',
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
