# Generated by Django 3.1.2 on 2020-10-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20201016_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='set_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
